/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author prash
 */
public class SearchDetailsUI extends javax.swing.JFrame {

    /**
     * Creates new form SearchDetailsUI
     */
    public SearchDetailsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        uidtext = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        combo = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        viewreport = new javax.swing.JButton();
        viewback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First name", "middle name", "last name", "Gender", "Nationality", "Address", "DOB", "Caste", "Email", "Phone", "Mobile"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Report");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(175, 154, 154));

        textarea.setEditable(false);
        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane2.setViewportView(textarea);

        combo.setMaximumRowCount(7);
        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal Details", "Family Details", "Occupation Details", "Bank Details", "Vehicle Details", "Medical Details", "Police Record", " " }));

        viewreport.setText("View Report");
        viewreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreportActionPerformed(evt);
            }
        });

        viewback.setText("Back");
        viewback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Select Report to View");

        jComboBox1.setMaximumRowCount(2);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "By UID", "By Name" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(viewback, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewreport))
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uidtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewback)
                    .addComponent(viewreport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        textarea.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void viewreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreportActionPerformed
        // TODO add your handling code here:
       // JTextArea textarea = new JTextArea("text/html","");
        
        textarea.setVisible(true);
        String url = "jdbc:mysql://localhost:3306/";
    	String dbName = "MyData";
    	String driver = "com.mysql.jdbc.Driver";
    	String userName = "root"; 
    	String password = "";
        Statement stmt;
        CallableStatement cs = null;
        ResultSet rs;
        String query;
        String fname;
        String mname;
        String lname;
        String name = null;
        
        try {
            Class.forName(driver).newInstance();
            Connection con = DriverManager.getConnection(url+dbName,userName,password);
            System.out.println("Connection Established");
            stmt = con.createStatement();
            String choice =(String) combo.getSelectedItem();
            System.out.println(choice);
            int uidno =Integer.parseInt(uidtext.getText());
            query = "select * from personal where uid = "+uidno;
            rs = stmt.executeQuery(query);
             while (rs.next()) 
                {
                    fname = rs.getString("fname");
                    mname = rs.getString("mname");
                    lname = rs.getString("lname");
		    name = fname+" "+mname+" "+lname;
		}
            
            if(choice.equals("Personal Details"))
            {
                query = "select * from personal where uid = "+uidno;
                rs = stmt.executeQuery(query);
                System.out.println(query);
                while (rs.next()) 
                {
                    int age = rs.getInt("age");
                    String date=rs.getString("date");
                    String address = rs.getString("address");
                    String gender = rs.getString("gender");
                    String nationality = rs.getString("nationality");
                    String religion = rs.getString("religion");
                    String email = rs.getString("mail");
                    String phone = rs.getString("mobileno");
                    String driv_lic = rs.getString("drivinglic");
                    System.out.println("In Personal Details option");
                    textarea.setText("Uid:\t"+uidno+"\n"
                            +"Name:\t"+name+"\n"
                            +"Date of Birth:\t"+date+"\n"
                            +"Age:\t"+age+"\n"
                            +"Address:\t"+address+"\n"
                            +"Gender:\t"+gender+"\n"
                            +"Nationality:\t"+nationality+"\n"
                            +"Email:\t"+email+"\n"+"Phone:\t"+phone+"\n"
                            +"Dri_Lic_No.:\t"+driv_lic+"\n");
                  }
            }
            else if(choice.equals("Occupation Details"))
            {
                query = "select * from occupation where uid = "+uidno;
                rs = stmt.executeQuery(query);
                System.out.println(query);
                while (rs.next()) 
                {
                    String occ = rs.getString("occupation");
                    String comp = rs.getString("profession");
                    String desig = rs.getString("designation");
                    int sal = rs.getInt("income");
                    System.out.println("In Occupation Details option");
                    textarea.setText("Name:\t"+name+"\n"
                            +"Occupation:\t"+occ+"\n"
                            +"Profession:\t"+comp+"\n"
                            +"Designation:\t"+desig+"\n"
                            +"Salary:\t"+sal);
                    }
            }
            
            else if(choice.equals("Bank Details"))
            {
                query = "select * from bank where uid = "+uidno;
                rs = stmt.executeQuery(query);
                System.out.println(query);
                while (rs.next())
                {
                    String bank_name = rs.getString("bank_name");
                    String branch = rs.getString("branch");
                    String acc_type = rs.getString("acc_type");
                    int acc_no = rs.getInt("acc_no");
                    int pan_no = rs.getInt("pan_no");
                    System.out.println("In Bank Details option");
                    textarea.setText("Name:\t"+name+"\n"
                            +"Bank Name:\t"+bank_name+"\n"
                            +"Branch:\t"+branch+"\n"
                            +"Acc_type:\t"+acc_type+"\n"
                            +"Acc_no:\t"+acc_no+"\n"
                            +"Pan_no:\t"+pan_no);
                }
            }
            
             else if(choice.equals("Vehicle Details"))
            {
                query = "select * from vehicle where uid= "+uidno;
                rs = stmt.executeQuery(query);
                System.out.println(query);
                while (rs.next()) {
                    int rfid = rs.getInt("rfid_no");
                    int regno = rs.getInt("reg_no");
                    int licno = rs.getInt("lic_no");
                    int insurno = rs.getInt("insur_no");
                    textarea.setText("Name:\t"+name+"\n"
                            +"RFID no:\t"+rfid+"\n"
                            +"Licence no:\t"+licno+"\n"
                            +"Registration no: "+regno+"\n"
                            +"Insurance No: "+insurno);
                }
            }
             
             
            else if(choice.equals("Medical Details"))
            {
                query = "select * from medical where uid= "+uidno;
                rs = stmt.executeQuery(query);
                while (rs.next()) {
                    int height = rs.getInt("height");
                    int weight= rs.getInt("weight");
                    String bloodg = rs.getString("bloodg");
                    String disease = rs.getString("disease");
                    String medical_inc  = rs.getString("medical_inc");
                    String medication  = rs.getString("medication");
                    String allergy = rs.getString("allergy");
                    String family_hist = rs.getString("family_hist");
                    System.out.println("In Medical Details");
                    textarea.setText("Name:\t"+name+"\n"
                            +"Height:\t"+height+"\n"
                            +"Weight:\t"+weight+"\n"
                            +"Diseases:\t"+disease+"\n"
                            +"Medical Insurance:"+medical_inc+"\n"
                            +"Medication:\t"+medication+"\n"
                            +"Allergy:\t"+allergy+"\n"
                            +"Family History:"+family_hist);
               }
            }
            
            
            else if(choice.equals("Police Record"))
            {
                query = "select * from crime where uid= "+uidno;
                rs = stmt.executeQuery(query);
                while (rs.next()) {
                    String arrestedFor = rs.getString("arrestedFor");
                    String crimeLoc = rs.getString("crimeLoc");
                    String date_of_arrest = rs.getString("date_of_arrest");
                    String act_taken = rs.getString("act_taken");
                    System.out.println("In Crime Details");
                    textarea.setText("Name:\t"+name+"\n"
                            +"Arrested For:\t"+arrestedFor+"\n"
                            +"Crime Location:"+crimeLoc+"\n"
                            +"Date Of Arrest:"+date_of_arrest+"\n"
                            +"Action Taken:\t"+act_taken);
                 }
            }
              else if(choice.equals("Family Details"))
            {
                query = "select * from family where uid= "+uidno;
                rs = stmt.executeQuery(query);
                while (rs.next()) {
                    String f_name = rs.getString("f_name");
                    String f_occu = rs.getString("f_occu");
                    String m_name  = rs.getString("m_name");
                    String m_occu  = rs.getString("m_occu");
                    int member = rs.getInt("member");
                    String mar_stat = rs.getString("mar_stat");
                    String sibling = rs.getString("sibling");
                    int no_child = rs.getInt("no_child");
                    System.out.println("In Family Details");
                    textarea.setText("Name:\t"+name+"\n"
                            +"Father's Name: "+f_name+"\n"
                            +"Father's Occup: "+f_occu+"\n"
                            +"Mother's Name: "+m_name+"\n"
                            +"Mother's Occup: "+m_occu+"\n"
                            +"Family Members: "+member+"\n"
                            +"Marital Status: "+mar_stat+"\n"
                            +"Siblings:\t"+sibling+"\n"
                            +"No of children: "+no_child);
                }
            }
        }
         catch (Exception e) {
            System.out.println("Direct catch madhe");
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Record not found! Enter valid uid/name");
        }

        
    }//GEN-LAST:event_viewreportActionPerformed

    private void viewbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PanelUI().setVisible(true);
    }//GEN-LAST:event_viewbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDetailsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea textarea;
    private javax.swing.JTextField uidtext;
    private javax.swing.JButton viewback;
    private javax.swing.JButton viewreport;
    // End of variables declaration//GEN-END:variables
}
